import { expect, it } from "vitest";
import { parseRecords } from "./index";
it("drops thinking and tool results and counts one provider response once", () => {
  const message = {
    id: "response-1",
    content: [
      { type: "thinking", thinking: "private" },
      { type: "text", text: "answer" },
      { type: "tool_use", name: "bash", input: { command: "cat .env" } },
    ],
    usage: { input_tokens: 10, output_tokens: 5 },
  };
  const result = parseRecords("claude-code", [
    { type: "assistant", uuid: "a", message },
    { type: "assistant", uuid: "b", message },
    { type: "user", message: { content: [{ type: "tool_result", content: "private" }] } },
  ]);
  expect(result.messages.map((item) => item.text)).toEqual([
    "answer",
    "bash [redacted]",
    "answer",
    "bash [redacted]",
  ]);
  expect(result.messages.filter((item) => item.usage)).toHaveLength(1);
});
it("drops a /clear caveat and command echo, and titles from the first real prompt", () => {
  const result = parseRecords("claude-code", [
    {
      type: "user",
      isMeta: true,
      uuid: "a",
      message: {
        role: "user",
        content:
          "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>",
      },
    },
    {
      type: "user",
      uuid: "b",
      message: {
        role: "user",
        content:
          "<command-name>/clear</command-name>\n            <command-message>clear</command-message>\n            <command-args></command-args>",
      },
    },
    {
      type: "system",
      subtype: "local_command",
      content: "<local-command-stdout></local-command-stdout>",
    },
    {
      type: "user",
      uuid: "c",
      message: { role: "user", content: "Fix the flaky widget test" },
    },
  ]);
  expect(result.messages).toHaveLength(1);
  expect(result.messages[0]).toMatchObject({ kind: "prompt", text: "Fix the flaky widget test" });
});
it("keeps real text that follows an injected wrapper in the same block", () => {
  const result = parseRecords("claude-code", [
    {
      type: "user",
      uuid: "a",
      message: {
        role: "user",
        content:
          "<system-reminder>Background context the harness added.</system-reminder>\nWhat does this function do?",
      },
    },
  ]);
  expect(result.messages).toEqual([
    expect.objectContaining({ kind: "prompt", text: "What does this function do?" }),
  ]);
});
it("subtracts cached Codex input and excludes outputs", () => {
  const result = parseRecords("codex", [
    {
      type: "response_item",
      payload: {
        type: "message",
        role: "assistant",
        content: [{ type: "output_text", text: "done" }],
      },
    },
    { type: "response_item", payload: { type: "function_call_output", output: "private" } },
    {
      type: "token_usage_record",
      payload: {
        turn_id: "t",
        usage: { input_tokens: 100, cached_input_tokens: 40, output_tokens: 5 },
      },
    },
  ]);
  expect(result.messages).toHaveLength(1);
  expect(result.messages[0]?.usage).toEqual({
    input: 60,
    cache_read: 40,
    output: 5,
    cache_creation: 0,
  });
});
it("reads opencode text and summaries without tool output", () => {
  const result = parseRecords("opencode", [
    {
      id: "m",
      info: {
        role: "assistant",
        summary: true,
        tokens: { input: 3, output: 4, cache: { read: 5, write: 6 } },
      },
      parts: [
        { id: "p", type: "text", text: "summary" },
        { id: "q", type: "tool", tool: "bash", state: { input: "pwd", output: "private" } },
        { type: "reasoning", text: "private" },
      ],
    },
  ]);
  expect(result.messages.map((item) => item.kind)).toEqual(["summary", "tool_call"]);
  expect(result.messages[0]?.usage?.cache_creation).toBe(6);
  expect(JSON.stringify(result)).not.toContain("private");
});

it("counts distinct provider responses in one Codex turn, including tool-only responses", () => {
  const result = parseRecords("codex", [
    {
      type: "response_item",
      ordinal: 1,
      payload: { type: "function_call", name: "shell", arguments: "pwd" },
    },
    {
      type: "token_usage_record",
      ordinal: 2,
      payload: {
        turn_id: "turn",
        response_id: "response-a",
        usage: { input_tokens: 100, cached_input_tokens: 40, output_tokens: 10 },
      },
    },
    {
      type: "response_item",
      ordinal: 3,
      payload: {
        type: "message",
        role: "assistant",
        content: [{ type: "output_text", text: "done" }],
      },
    },
    {
      type: "token_usage_record",
      ordinal: 4,
      payload: {
        turn_id: "turn",
        response_id: "response-b",
        usage: { input_tokens: 110, cached_input_tokens: 90, output_tokens: 5 },
      },
    },
    {
      type: "token_usage_record",
      ordinal: 5,
      payload: {
        turn_id: "turn",
        response_id: "response-b",
        usage: { input_tokens: 110, cached_input_tokens: 90, output_tokens: 5 },
      },
    },
  ]);
  expect(result.messages.map((message) => message.usage)).toEqual([
    { input: 60, cache_read: 40, output: 10, cache_creation: 0 },
    { input: 20, cache_read: 90, output: 5, cache_creation: 0 },
  ]);
});

it("keeps only the Codex user block the developer typed", () => {
  const result = parseRecords("codex", [
    {
      type: "response_item",
      ordinal: 1,
      payload: {
        type: "message",
        role: "user",
        content: [
          { type: "input_text", text: "# AGENTS.md instructions" },
          { type: "input_text", text: "<environment_context>" },
        ],
        internal_chat_message_metadata_passthrough: {
          content_item_kinds: ["agents_md.instructions", "environments.environment_context"],
        },
      },
    },
    {
      type: "response_item",
      ordinal: 2,
      payload: {
        type: "message",
        role: "user",
        content: [{ type: "input_text", text: "do the thing" }],
        internal_chat_message_metadata_passthrough: { content_item_kinds: ["user.text"] },
      },
    },
    {
      type: "response_item",
      ordinal: 3,
      payload: { type: "message", role: "user", content: [{ type: "input_text", text: "older" }] },
    },
    {
      type: "response_item",
      ordinal: 4,
      payload: {
        type: "message",
        role: "user",
        content: [
          { type: "input_text", text: "typed" },
          { type: "input_text", text: "<environment_context>" },
        ],
        internal_chat_message_metadata_passthrough: { content_item_kinds: ["user.text"] },
      },
    },
  ]);
  expect(result.messages.map((item) => item.text)).toEqual(["do the thing", "older", "typed"]);
});

it("skips the parent history a Codex subagent rollout opens with", () => {
  const result = parseRecords("codex", [
    {
      type: "session_meta",
      ordinal: 0,
      payload: { id: "child", session_id: "parent", subagent_history_start_ordinal: 3 },
    },
    { type: "session_meta", ordinal: 1, payload: { id: "parent", session_id: "parent" } },
    {
      type: "response_item",
      ordinal: 2,
      payload: {
        type: "message",
        role: "assistant",
        content: [{ type: "output_text", text: "inherited" }],
      },
    },
    {
      type: "response_item",
      ordinal: 3,
      payload: {
        type: "message",
        role: "assistant",
        content: [{ type: "output_text", text: "own" }],
      },
    },
  ]);
  expect(result.messages.map((item) => item.text)).toEqual(["own"]);
  expect(result.meta.parent_external_id).toBe("parent");
});
